name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      
      - name: Build
        run: go build .
      
      - name: Test with coverage
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      
      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1